import type React from "react";
import type { Metadata } from "next";
import "./globals.css";
import { copernicus } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${copernicus.variable} antialiased`}>{children}</body>
    </html>
  );
}
